/**
 * Doctor specializations commonly used in Indian healthcare.
 * Single source of truth — import from here instead of duplicating lists.
 */
export const medicalSpecializations = [
  "General Physician",
  "Family Medicine",
  "Internal Medicine",
  "Emergency Medicine",
  "Critical Care Specialist",
  "Anesthesiologist",
  "Cardiologist",
  "Cardiothoracic Surgeon",
  "Vascular Surgeon",
  "Interventional Cardiologist",
  "Dermatologist",
  "Cosmetologist",
  "Trichologist",
  "Dentist",
  "Orthodontist",
  "Oral & Maxillofacial Surgeon",
  "Periodontist",
  "ENT Specialist",
  "Audiologist",
  "Speech Therapist",
  "Ophthalmologist",
  "Gastroenterologist",
  "Hepatologist",
  "General Surgeon",
  "Laparoscopic Surgeon",
  "Bariatric Surgeon",
  "Neurosurgeon",
  "Plastic & Reconstructive Surgeon",
  "Orthopedic Surgeon",
  "Sports Medicine Specialist",
  "Rheumatologist",
  "Gynecologist",
  "Obstetrician",
  "Gynecologist & Obstetrician",
  "Neonatologist",
  "Pediatrician",
  "Pediatric Surgeon",
  "IVF & Fertility Specialist",
  "Andrologist",
  "Urologist",
  "Nephrologist",
  "Endocrinologist",
  "Diabetologist",
  "Pulmonologist",
  "Allergist & Immunologist",
  "Infectious Disease Specialist",
  "Oncologist",
  "Medical Oncologist",
  "Radiation Oncologist",
  "Hematologist",
  "Neurologist",
  "Psychiatrist",
  "Psychologist",
  "Clinical Psychologist",
  "Counselor",
  "Geriatrician",
  "Pain Management Specialist",
  "Sleep Medicine Specialist",
  "Palliative Care Specialist",
  "Physiotherapist",
  "Occupational Therapist",
  "Chiropractor",
  "Nutritionist",
  "Dietitian",
  "Sexologist",
  "Radiologist",
  "Pathologist",
  "Microbiologist",
  "Medical Geneticist",
  "Podiatrist",
  "Ayurveda",
  "Homeopathy",
  "Unani",
  "Siddha",
  "Naturopathy",
  "Yoga Therapist",
] as const

export type MedicalSpecialization = (typeof medicalSpecializations)[number]

/** For search/filter dropdowns */
export const medicalSpecializationFilterOptions = [
  "All Specializations",
  ...medicalSpecializations,
] as const

// Common medical services
export const medicalServices = [
  "General Consultation",
  "Follow-up Consultation",
  "Health Checkup",
  "Blood Test",
  "X-Ray",
  "ECG",
  "Ultrasound",
  "MRI",
  "CT Scan",
  "Vaccination",
  "Minor Surgery",
  "Dental Cleaning",
  "Dental Filling",
  "Root Canal",
  "Eye Examination",
  "Skin Treatment",
  "Hair Treatment",
  "Physiotherapy",
  "Occupational Therapy",
  "Speech Therapy",
  "Diet Counseling",
  "Mental Health Counseling",
  "Pregnancy Care",
  "Child Care",
  "Diabetes Management",
  "Hypertension Management",
  "Thyroid Treatment",
  "Allergy Testing",
  "Asthma Treatment",
  "Heart Checkup",
  "Kidney Function Test",
  "Liver Function Test",
  "Bone Density Test",
  "IVF Consultation",
  "Pain Management",
  "Sports Injury Rehab",
  "Post-operative Rehab",
  "Telemedicine Consultation",
]

// Consultation fee ranges
export const feeRanges = [
  { label: "Under ₹200", min: 0, max: 200 },
  { label: "₹200 - ₹500", min: 200, max: 500 },
  { label: "₹500 - ₹1000", min: 500, max: 1000 },
  { label: "₹1000 - ₹2000", min: 1000, max: 2000 },
  { label: "Above ₹2000", min: 2000, max: 100000 },
]
