// Medical Specializations in India
export const medicalSpecializations = [
    "General Physician",
    "Cardiologist",
    "Dermatologist",
    "Dentist",
    "ENT Specialist",
    "Gastroenterologist",
    "General Surgeon",
    "Gynecologist",
    "Neurologist",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic",
    "Pediatrician",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Urologist",
    "Nephrologist",
    "Endocrinologist",
    "Rheumatologist",
    "Ayurveda",
    "Homeopathy",
    "Physiotherapist",
    "Nutritionist",
    "Psychologist",
];

// Common medical services
export const medicalServices = [
    "General Consultation",
    "Health Checkup",
    "Blood Test",
    "X-Ray",
    "ECG",
    "Ultrasound",
    "MRI",
    "CT Scan",
    "Vaccination",
    "Minor Surgery",
    "Dental Cleaning",
    "Dental Filling",
    "Root Canal",
    "Eye Examination",
    "Skin Treatment",
    "Hair Treatment",
    "Physiotherapy",
    "Diet Counseling",
    "Mental Health Counseling",
    "Pregnancy Care",
    "Child Care",
    "Diabetes Management",
    "Hypertension Management",
    "Thyroid Treatment",
    "Allergy Testing",
    "Asthma Treatment",
    "Heart Checkup",
    "Kidney Function Test",
    "Liver Function Test",
    "Bone Density Test",
];

// Consultation fee ranges
export const feeRanges = [
    { label: "Under ₹200", min: 0, max: 200 },
    { label: "₹200 - ₹500", min: 200, max: 500 },
    { label: "₹500 - ₹1000", min: 500, max: 1000 },
    { label: "₹1000 - ₹2000", min: 1000, max: 2000 },
    { label: "Above ₹2000", min: 2000, max: 100000 },
];
